version: '3'

services: 

    nodejs:
        build:
            context: ./node
        image: mmagrinelli/nodejs:prod
        container_name: nodejs
        networks: 
            - nginx-nodejs-net
        tty: true
        depends_on: 
            - db

    nginx:
        build:
            context: ./nginx
        image: mmagrinelli/nginx:prod
        container_name: nginx
        networks: 
            - nginx-nodejs-net
        ports: 
            - "8080:80"
        depends_on: 
            - nodejs

    db:
        image: mysql:5.7
        command: --innodb-use-native-aio=0
        container_name: db
        restart: always
        tty: true
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=nodedb
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - nginx-nodejs-net

networks: 
    nginx-nodejs-net:
        driver: bridge